add eupl license
rafamadriz/friendly-snippets pull request #206
Opened 2022-11-20 22:40 UTC by koopa1338

Added EUPL license to global snippets. The long lines can also be separated, but I wanted to keep it as original as I could.

2022-11-20 22:41 UTC, kerkmann commented
lgtm; :)

2022-11-20 22:41 UTC, kerkmann approved these changes

2022-11-27 04:05 UTC, OkelleyDevelopment requested changes
Hey @koopa1338 :wave: 

Before `lgtm` can happen, could you double check the link (on line 389) in the PR? 

When I tested, it brought me to a 404 page which I doubt is the intent here :sweat_smile: 


Once that's resolved then we can get this merged! :sunglasses:

2022-11-27 12:22 UTC, kerkmann requested changes

2022-11-27 12:22 UTC, kerkmann commented on snippets/global.json
> +      "<https://joinup.ec.europa.eu/software/page/eupl5>",
```suggestion
      "<https://joinup.ec.europa.eu/software/page/eupl>",
```
@OkelleyDevelopment Indeed, you're right. Seems like that the `5` was accidentally added. :)

2022-11-28 20:44 UTC, koopa1338 commented
Fixed URL with a284e0a

2022-11-29 02:18 UTC, OkelleyDevelopment approved these changes
Epic thanks for checking @koopa1338  @kerkmann 

Lgtm! :sunglasses:

2022-11-29 02:19 UTC, merged