improve/add C snippets for control and loops
rafamadriz/friendly-snippets pull request #232
Opened 2023-01-13 20:24 UTC by REmerald

Improve formatting for these snippets; add some useful snippets.

2023-01-17 02:53 UTC, OkelleyDevelopment commented
Hey @REmerald , I merged the other PR that resolve the issue so the snippets function for others while I review this PR. 

Note: You can resolve the conflict by removing the `"",` that you'd added in that last commit. If you wished for the newlines to be present, then simply add `\n`, ideally I want to really minimize the "dead space" used for stuff like `"",` especially on the new PRs we accept. 

Once that's resolved I can give this the approval and get this merged :sunglasses:

2023-01-17 13:18 UTC, REmerald commented
Removed `"",` for now, maybe I'll add `\n` later in my next pull requests.

2023-01-18 00:41 UTC, OkelleyDevelopment requested changes
Thank you for the last update, everything still looks good except for the 3 spots missing commas. 

I'm watching this PR tonight, so if you get these changes made in the next few hours then I will review asap so we can close this out :sunglasses:

2023-01-18 00:41 UTC, OkelleyDevelopment commented on snippets/c.json
> +      "typedef enum $1 ${1:Numbers};"
Need a comma here

2023-01-18 00:41 UTC, OkelleyDevelopment commented on snippets/c.json
> +      "typedef union $1 ${1:Cell};"
Add a comma here

2023-01-18 00:41 UTC, OkelleyDevelopment commented on snippets/c.json
> +      "typedef struct $1 ${1:Box};"
Add a comma here too

2023-01-18 11:10 UTC, REmerald commented on snippets/c.json
> +      "typedef struct $1 ${1:Box};"
fixed

2023-01-18 11:10 UTC, REmerald commented on snippets/c.json
> +      "typedef union $1 ${1:Cell};"
fixed

2023-01-18 11:11 UTC, REmerald commented on snippets/c.json
> +      "typedef enum $1 ${1:Numbers};"
fixed

2023-01-19 05:36 UTC, OkelleyDevelopment approved these changes
I believe these are acceptable, good work :sunglasses:

2023-01-19 05:38 UTC, merged