angular snippets
rafamadriz/friendly-snippets pull request #355
Opened 2023-08-16 15:52 UTC by sirstanislav

Hye. Can you add pls angular snippets from [here](https://github.com/johnpapa/vscode-angular-snippets/tree/main/snippets)

![Screenshot 2023-08-16 at 17 49 14](https://github.com/rafamadriz/friendly-snippets/assets/74570672/3dbcd316-ddf4-42f2-b686-3d67718fc34e)
![Screenshot 2023-08-16 at 17 50 28](https://github.com/rafamadriz/friendly-snippets/assets/74570672/d70bb87c-295d-4bc8-a270-3e44b100a2ee)

2023-08-27 08:02 UTC, OkelleyDevelopment requested changes
Overall the PR looks good just a few nit-picks. If you disagree with my perspective please do expand on your reasoning so I can better understand the inclusion of certain snippets! :grin:

2023-08-27 08:02 UTC, OkelleyDevelopment commented on snippets/frameworks/angular/dockerfile.json
> +  "Multi-stage Node and Angular Dockerfile": {
Similar to my other comment, this seems like it could be omitted from this PR (and retain the focus on adding the Angular snippets).

2023-08-28 09:28 UTC, sirstanislav commented
I think you are right. Be honest i don't use this snippets to create docker file or to launch node.js server. I think they was added from author for personal use. And we can remove they leaving only general. Sorry for commits history. Some things i do first time.

2023-09-02 21:11 UTC, OkelleyDevelopment approved these changes

2023-09-03 02:11 UTC, merged