Add Beancount snippets
rafamadriz/friendly-snippets pull request #424
Opened 2024-03-26 12:06 UTC by marvielb

Add support for Beancount.
From [vscode-beancount](https://github.com/Lencerf/vscode-beancount)'s [snippet](https://github.com/Lencerf/vscode-beancount/blob/master/snippets/beancount.json). Created by [vlamacko](https://github.com/vlamacko).

2024-03-31 16:43 UTC, OkelleyDevelopment reviewed
From a cursory look at the docs, these look good to me. Have you tested these locally to confirm the output is what you intended?

2024-03-31 16:57 UTC, OkelleyDevelopment requested changes
See my other question, but also please rebase on the latest main branch to resolve the issue with `package.json`. 

If you need any assistance/clarifications, do let me know!

2024-03-31 23:50 UTC, marvielb commented
Yes @OkelleyDevelopment I have tested this locally and currently using it. I pushed an update to the conflict, thanks!

2024-04-29 01:07 UTC, OkelleyDevelopment approved these changes

2024-04-29 01:08 UTC, merged