Update R/`shinymod` snippet
rafamadriz/friendly-snippets pull request #469
Opened 2024-06-14 22:59 UTC by wurli

The previously used module syntax has been deprecated since 2020, see [Mastering Shiny](https://mastering-shiny.org/scaling-modules.html#updated-app) for details.

Thanks!

2024-06-17 03:35 UTC, OkelleyDevelopment requested changes
Thanks for the PR! Just a small change needed before we can land this into main. :sunglasses:

2024-06-17 03:35 UTC, OkelleyDevelopment commented on snippets/r.json
> +            "    ${3}"
I believe the line containing the `${3}` needs a comma, else this will throw an error.

2024-07-08 03:37 UTC, OkelleyDevelopment commented
Any updates on this PR @wurli ?

2024-07-09 16:44 UTC, wurli commented
Sorry for the late response! Just started a new job and a few things dropped off my radar. Thanks for the reminder and good catch! Just made the change.

2024-07-15 00:33 UTC, OkelleyDevelopment approved these changes
Thanks for the update and congrats on the new job! :rocket:

2024-07-15 00:33 UTC, merged